// 5.vue-webpack/src/Todo/index.vue
<template>
  <div>
    <todo-list :todos="todos" @click="handleClick" />
    <add-todo-form @submit="handleSubmit" />
  </div>
</template>
<script>
import TodoList from './TodoList'
import AddTodoForm from './AddTodoForm'
import uuid from 'uuid'

export default {
  components: { TodoList, AddTodoForm },
  data: () => ({
    // { id: <Number>, text: <String>, completed: <Boolean> }
    todos: []
  }),
  methods: {
    handleClick (todoId) {
      this.todos = this.todos.map(todo => {
        if (todo.id === todoId) {
          todo.completed = !todo.completed
        }
        return todo
      })
    },
    handleSubmit (text) {
      this.todos.push({
        id: uuid(),
        text,
        completed: false
      })
    }
  }
}
</script>

// 4.react-webpack/src/Todo/index.js
import React, { Component } from 'react'
import TodoList from './TodoList'
import AddTodoForm from './AddTodoForm'
import uuid from 'uuid'

export default class Todo extends Component {

  constructor (props) {
    super(props)
    this.state = {
      todos: [] // [{ id: <Number>, text: <String>, completed: <Boolean> }]
    }
  }

  handleClick (todoId) {
    this.setState({
      todos: this.state.todos.map(todo => {
        if (todo.id === todoId) {
          todo.completed = !todo.completed
        }
        return todo
      })
    })
  }

  handleSubmit (text) {
    this.setState({
      todos: [
        ...this.state.todos,
        {
          id: uuid(),
          text,
          completed: false
        }
      ]
    })
  }

  render () {
    const { todos } = this.state
    return (
      <div>
        <TodoList todos={todos} handleClick={this.handleClick.bind(this)} />
        <AddTodoForm todos={todos} handleSubmit={this.handleSubmit.bind(this)} />
      </div>
    )
  }

}
