// 4.react-webpack/src/Todo/TodoList.js
import React, { Component } from 'react'
import injectSheet from 'react-jss'

// CSS in JS
const styles = {
  finished: {
    color: 'gray',
    textDecoration: 'line-through'
  },
  unfinished: {
    color: 'red',
    fontWeight: 'bold'
  }
}

@injectSheet(styles)
export default class TodoList extends Component {
  render () {
    const { todos, handleClick, classes } = this.props
    return (
      <ul>
        { todos.map(todo => 
          <li key={todo.id}
            onClick={() => handleClick(todo.id)}
            className={todo.completed ? classes.finished : classes.unfinished}>
            { todo.text }
          </li>
        )}
      </ul>
    )
  }
}

// 5.vue-webpack/src/Todo/TodoList.vue
<template>
  <ul>
    <li v-for="todo in todos" @click="$emit('click', todo.id)"
      :class="todo.completed ? 'finished' : 'unfinished'">
      {{ todo.text }}
    </li>
  </ul>
</template>
<script>
export default {
  props: ['todos']
}
</script>
<style>
.finished {
  color: gray;
  text-decoration: line-through;
}
.unfinished {
  color: red;
  font-weight: bold;
}
</style>
